[env]
CONFIG_FILE = { value = "config/config.toml", relative = true }

RUST_LOG = 'trace'

# MIMALLOC_SHOW_STATS = '1'
# MIMALLOC_VERBOSE    = '1'


[target.x86_64-unknown-linux-gnu]
rustflags = ["-Ctarget-cpu=native"]


[net]
git-fetch-with-cli = true
